use_gpu: True

# training
train_split: train
train_lr: 0.01
train_lr_adjust_rate: 0.1
train_lr_adjust_freq: 5
train_epoch_num: 20
train_save_freq: 5
train_print_freq: 10
train_batch_size: 32

# test_split: test
test_split: val
test_epoch: 20
test_batch_size: 64


# paths
data_root: data
cache_root: cache
output_root: output
checkpoint_root: checkpoint













